// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class tinkoff : Exchange
{
    public tinkoff (object args = null): base(args) {}

    public async Task<object> instrumentsPostEtfs (object parameters = null)
    {
        return await this.callAsync ("instrumentsPostEtfs",parameters);
    }

    public async Task<object> marketdataPostGetLastTrades (object parameters = null)
    {
        return await this.callAsync ("marketdataPostGetLastTrades",parameters);
    }

    public async Task<object> marketdataPostGetOrderBook (object parameters = null)
    {
        return await this.callAsync ("marketdataPostGetOrderBook",parameters);
    }

    public async Task<object> marketdataPostGetCandles (object parameters = null)
    {
        return await this.callAsync ("marketdataPostGetCandles",parameters);
    }

    public async Task<object> ordersPostPostOrder (object parameters = null)
    {
        return await this.callAsync ("ordersPostPostOrder",parameters);
    }

    public async Task<object> ordersPostCancelOrder (object parameters = null)
    {
        return await this.callAsync ("ordersPostCancelOrder",parameters);
    }

    public async Task<object> ordersPostGetOrderState (object parameters = null)
    {
        return await this.callAsync ("ordersPostGetOrderState",parameters);
    }

    public async Task<object> ordersPostGetOrders (object parameters = null)
    {
        return await this.callAsync ("ordersPostGetOrders",parameters);
    }

}